[package]
name = "graphics-adapter-vulkan"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4.22"
raw-window-handle = "0.3.4"
vulkanalia = { version = "=0.16.0", features = ["libloading", "window"] }

engine = { path = "../engine" }
